name: Terraform Plan & Apply Infrastructure

on:
  push:
    branches: ['main']
    paths:
      - 'infrastructure/**'
    tags:
      - '*'
  workflow_dispatch:

env:
  WORKING_DIRECTORY: './infrastructure'

jobs:
  terraform:
    runs-on: ubuntu-latest
    environment: production
    permissions:
      id-token: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Azure login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_ENTRA_ID_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_ENTRA_ID_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.8.4

      - name: Terraform fmt
        id: fmt
        run: terraform fmt -check
        continue-on-error: true

      - name: Terraform Init
        id: init
        working-directory: ${{ env.WORKING_DIRECTORY }}
        env:
          ARM_CLIENT_ID: ${{ secrets.AZURE_ENTRA_ID_CLIENT_ID }}
          ARM_TENANT_ID: ${{ secrets.AZURE_ENTRA_ID_TENANT_ID }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          ARM_USE_OIDC: true
          TF_VAR_bus_string: ${{ secrets.SERVICE_BUS_CONNECTION_STRING  }}
          TF_VAR_acs_string: ${{ secrets.ACS_CONNECTION_STRING  }}
          TF_VAR_acs_addr: ${{ secrets.ACS_SENDER_ADDRESS }}
          TF_VAR_db_uri: ${{ secrets.DATABASE_URI }}
        run: terraform init -var="bus_string=${{ secrets.SERVICE_BUS_CONNECTION_STRING }}" -var="acs_string=${{ secrets.ACS_CONNECTION_STRING }}" -var="acs_addr=${{ secrets.ACS_SENDER_ADDRESS }}" -var="db_uri=${{ secrets.DATABASE_URI }}"

      - name: Terraform Validate
        id: validate
        working-directory: ${{ env.WORKING_DIRECTORY }}
        run: terraform validate -no-color

      - name: Terraform Plan
        id: plan
        env:
          ARM_CLIENT_ID: ${{ secrets.AZURE_ENTRA_ID_CLIENT_ID }}
          ARM_TENANT_ID: ${{ secrets.AZURE_ENTRA_ID_TENANT_ID }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          ARM_USE_OIDC: true
          TF_VAR_bus_string: ${{ secrets.SERVICE_BUS_CONNECTION_STRING  }}
          TF_VAR_acs_string: ${{ secrets.ACS_CONNECTION_STRING  }}
          TF_VAR_acs_addr: ${{ secrets.ACS_SENDER_ADDRESS }}
          TF_VAR_db_uri: ${{ secrets.DATABASE_URI }}
        working-directory: ${{ env.WORKING_DIRECTORY }}
        run: terraform plan -no-color -var="bus_string=${{ secrets.SERVICE_BUS_CONNECTION_STRING }}" -var="acs_string=${{ secrets.ACS_CONNECTION_STRING }}" -var="acs_addr=${{ secrets.ACS_SENDER_ADDRESS }}" -var="db_uri=${{ secrets.DATABASE_URI }}"
        continue-on-error: false

      - name: Terraform Apply (auto-approve)
        working-directory: ${{ env.WORKING_DIRECTORY }}
        env:
          ARM_CLIENT_ID: ${{ secrets.AZURE_ENTRA_ID_CLIENT_ID }}
          ARM_TENANT_ID: ${{ secrets.AZURE_ENTRA_ID_TENANT_ID }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          ARM_USE_OIDC: true
          TF_VAR_bus_string: ${{ secrets.SERVICE_BUS_CONNECTION_STRING  }}
          TF_VAR_acs_string: ${{ secrets.ACS_CONNECTION_STRING  }}
          TF_VAR_acs_addr: ${{ secrets.ACS_SENDER_ADDRESS }}
          TF_VAR_db_uri: ${{ secrets.DATABASE_URI }}
        run: terraform apply -auto-approve -var="bus_string=${{ secrets.SERVICE_BUS_CONNECTION_STRING }}" -var="acs_string=${{ secrets.ACS_CONNECTION_STRING }}" -var="acs_addr=${{ secrets.ACS_SENDER_ADDRESS }}" -var="db_uri=${{ secrets.DATABASE_URI }}"